name: globetrotter
description: A travel app for discovering Cameroon.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.6
  geolocator: ^14.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  pointer_interceptor: ^0.10.1+2
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - web/
    - assets/images/
    - assets/images/dining/
    - assets/images/gaming/
    - assets/images/leisure/
    - assets/images/recreational/
    - assets/images/Schools/
    - assets/images/shopping/
    - assets/images/tourist/
